position = "top"
height = 24

[[start]]
type = "workspaces"

[[center]]
type = "focused"
icon_size = 16

[[end]]
type = "battery"
show_if = "ls /sys/class/power_supply/ | grep --quiet '^BAT'"

[[end]]
type = "sys_info"
format = [
    "{cpu_percent}% ",
    "{memory_percent}% ",
]

[end.interval]
cpu = 1

[[end]]
type = "tray"

[[end]]
type = "clock"

