anchor_to_edges: true
position: bottom
icon_theme: Paper
start:
- type: workspaces
  all_monitors: false
  name_map:
    '1': 󰙯
    '2': icon:firefox
    '3': 
    Games: icon:steam
    Code: 
- type: launcher
  favorites:
  - firefox
  - discord
  - steam
  show_names: false
  show_icons: true
- type: label
  label: 'random num: {{500:echo FIXME}}'
end:
- type: music
  player_type: mpd
  music_dir: /home/jake/Music
  truncate:
    mode: end
    max_length: 100
- type: music
  player_type: mpd
  host: chloe:6600
  truncate: end
- type: script
  cmd: /home/jake/bin/phone-battery
  show_if:
    cmd: /home/jake/bin/phone-connected
    interval: 500
- type: sys_info
  interval:
    memory: 30
    cpu: 1
    temps: 5
    disks: 300
    networks: 3
  format:
  -  {cpu_percent}% | {temp_c:k10temp_Tccd1}°C
  -  {memory_used} / {memory_total} GB ({memory_percent}%)
  - '| {swap_used} / {swap_total} GB ({swap_percent}%)'
  - 󰋊 {disk_used:/} / {disk_total:/} GB ({disk_percent:/}%)
  - 󰓢 {net_down:enp39s0} / {net_up:enp39s0} Mbps
  - 󰖡 {load_average:1} | {load_average:5} | {load_average:15}
  - 󰥔 {uptime}
- type: volume
  format: '{icon} {volume}%'
  max_volume: 100
  icons:
    volume_high: 󰕾
    volume_medium: 󰖀
    volume_low: 󰕿
    muted: 󰝟
- type: clipboard
  max_items: 3
  truncate:
    mode: end
    length: 50
- type: custom
  class: power-menu
  bar:
  - type: button
    name: power-btn
    label: 
    on_click: popup:toggle
  popup:
  - type: box
    orientation: vertical
    widgets:
    - type: label
      name: header
      label: Power menu
    - type: box
      widgets:
      - type: button
        class: power-btn
        label: <span font-size='40pt'></span>
        on_click: '!shutdown now'
      - type: button
        class: power-btn
        label: <span font-size='40pt'></span>
        on_click: '!reboot'
    - type: label
      name: uptime
      label: 'Uptime: {{30000:uptime -p | cut -d '' '' -f2-}}'
  tooltip: 'Up: {{30000:uptime -p | cut -d '' '' -f2-}}'
- type: clock

