name: PR Review
on:
  pull_request_review:

jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: github.event.pull_request.draft == false
    steps:
      - run: |
          gh pr edit "$NUMBER" --remove-label "Z:Review Required"
          gh pr edit "$NUMBER" --add-label "Z:Changes Requested"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}