name: Publish Schema

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'Cargo.*'
      - 'build.rs'
      - '.github/workflows/schema.yml'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-Dwarnings'

jobs:
  publish-schema:
    name: 'Publish Schema'
    runs-on: ubuntu-latest
    container: ghcr.io/jakestanger/ironbar-build:master

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies

      - name: Build
        run: cargo build --features schema

      - name: Print schema
        run: cargo run --features schema -- --print-schema > target/schema.json

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/schema.json"
          target: /storage/Public/github/ironbar
          strip_components: 1